name: A Basic Workflow

on:
  push:
    branches: ["main"]
    # ignore any branches
    #branches-ignore: ["ignore"]
    # Actions should run only when changes occur in this folder
    #paths: ".github/*"

  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  build-app:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Run one line script
          run: echo Hello, world!
        - name: Run a multiline script
          run: |
            echo Add other actions to biuld,
            echo test, and deploy your project.
  build-api-app:
    needs: build
    runs-on: windows-latest
  
  build-db
  packaging:
    needs: [build-app, build-api-app]
    runs-on: self-hosted
